<a href="https://colab.research.google.com/github/akitim/SkillFactory_current/blob/Aux1/Eigenpairs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A = np.array([[1, 4, 5],
    [-5, 8, 9],
    [-6, 7, 11]]) # создаем матрицу 3х3 
B = np.linalg.eig(A) # находим собственные вектора (с.в.) и собственные числа (с.ч.) через np.linalg.eig
B
# Обратите внимание, что B - кортеж (tuple). Его компоненты имеют тип np.ndarray, с которыми вы уже должны быть знакомы. 
# Нулевая компонента B[0] - вектор собственных чисел, а компонента B[1] - матрица, столбцами которой являются 
# собственные вектора, соответствующие данному числу.; в данном случае собственному числу 13.59373746 
# соответствует собственный вектор [0.45145779, 0.62348353, 0.63832135]

(array([13.59373746,  5.03209301,  1.37416954]),
 array([[ 0.45145779,  0.83661458,  0.10258363],
        [ 0.62348353,  0.44632316, -0.77299039],
        [ 0.63832135,  0.31760303,  0.62606905]]))

In [5]:
D = np.diagflat(B[0])
P = B[1]
P@D@np.linalg.inv(P)

array([[ 1.,  4.,  5.],
       [-5.,  8.,  9.],
       [-6.,  7., 11.]])