<a href="https://colab.research.google.com/github/akitim/SkillFactory_current/blob/main/Unit_2_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 9.2. О массивах NumPy

In [ ]:
import numpy as np
# np.set_printoptions(precision=2)
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[0, 5, 3],
       [3, 6, 0],
       [0, 6, 6]])

In [ ]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a = np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])
print(a)
a[0,1]

[[1 2 3 4 5]
 [5 1 2 3 4]
 [4 5 1 2 3]
 [3 4 5 1 2]
 [2 3 4 5 1]]


2

In [ ]:
np.random.randint(0, 5, 3)

array([3, 4, 3])

9.3. Индексирование массивов NumPy

In [ ]:
import numpy as np
np.set_printoptions(precision=2)
 
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]
 
big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
bg = big_secret
 
round(big_secret[:,-1].sum(),2)
 
round(big_secret[:, :5].trace(),2)
 
r = np.transpose([big_secret[:,-1]])
np.hstack((big_secret[:, -5:-1], r)).diagonal().prod()
 
m, n = bg.shape
#print (m, n)
 
bg[:,n-5:].diagonal().prod()

341505315559.2347

In [ ]:
import numpy as np
np.set_printoptions(precision=2)
 
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
 
great_secret = np.array([first, second, third]).T
gs = great_secret
gs.shape
 
round(np.cos(gs[0,:]).sum(),2)
 
gs[gs>50].sum()
 
gsf = gs.flatten()
gsf[150]
 
round (np.sort(gs, axis=0)[-1,:].sum(), 2)
#gs

115.12

In [ ]:
import numpy as np
np.set_printoptions(precision=2)
data = '''
1   135 34  4
2   160 43  5
3   163 40  4.3
4   147 44  5
5   138 41  4.7
6   149 54  3.9
7   136 39  4.2
8   154 48  4.9
9   137 35  3.7
10  165 60  4.6'''.split()
 
 
students = np.array(list(map (float, data)))
students.reshape(10,4)

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])