<a href="https://colab.research.google.com/github/akitim/SkillFactory_current/blob/main/Unit_2_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 9.2. О массивах NumPy

In [40]:
import numpy as np
# np.set_printoptions(precision=2)
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[0, 5, 3],
       [3, 6, 0],
       [0, 6, 6]])

In [ ]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
a = np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])
print(a)
a[0,1]

[[1 2 3 4 5]
 [5 1 2 3 4]
 [4 5 1 2 3]
 [3 4 5 1 2]
 [2 3 4 5 1]]


2

In [ ]:
np.random.randint(0, 5, 3)

array([3, 4, 3])

9.3. Индексирование массивов NumPy

In [81]:
import numpy as np
np.set_printoptions(precision=2)

first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
bg = big_secret

round(big_secret[:,-1].sum(),2)

round(big_secret[:, :5].trace(),2)

r = np.transpose([big_secret[:,-1]])
np.hstack((big_secret[:, -5:-1], r)).diagonal().prod()

bg[::2,::2] = -1
bg[1::2,1::2] = 1
bg
bg[:,:5].trace()

m,n = bg.shape
bg[:,n-5:].diagonal().prod()


-1.0

In [83]:
import numpy as np
np.set_printoptions(precision=2)

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
gs = great_secret
gs

array([[ 0.  ,  4.64, 66.67],
       [ 1.  ,  4.66, 40.  ],
       [ 1.41,  4.67, 67.33],
       [ 1.73,  4.69, 40.4 ],
       [ 2.  ,  4.7 , 68.  ],
       [ 2.24,  4.72, 40.8 ],
       [ 2.45,  4.73, 68.67],
       [ 2.65,  4.75, 41.2 ],
       [ 2.83,  4.76, 69.33],
       [ 3.  ,  4.78, 41.6 ],
       [ 3.16,  4.79, 70.  ],
       [ 3.32,  4.81, 42.  ],
       [ 3.46,  4.82, 70.67],
       [ 3.61,  4.83, 42.4 ],
       [ 3.74,  4.85, 71.33],
       [ 3.87,  4.86, 42.8 ],
       [ 4.  ,  4.88, 72.  ],
       [ 4.12,  4.89, 43.2 ],
       [ 4.24,  4.9 , 72.67],
       [ 4.36,  4.92, 43.6 ],
       [ 4.47,  4.93, 73.33],
       [ 4.58,  4.95, 44.  ],
       [ 4.69,  4.96, 74.  ],
       [ 4.8 ,  4.97, 44.4 ],
       [ 4.9 ,  4.99, 74.67],
       [ 5.  ,  5.  , 44.8 ],
       [ 5.1 ,  5.01, 75.33],
       [ 5.2 ,  5.03, 45.2 ],
       [ 5.29,  5.04, 76.  ],
       [ 5.39,  5.05, 45.6 ],
       [ 5.48,  5.07, 76.67],
       [ 5.57,  5.08, 46.  ],
       [ 5.66,  5.09, 77.33],
       [ 5